ERROR: 2020/03/26 16:40:49 log_test.go:11: Something has failed
